### ISSUE TITLE
Core : Thread leak

### ISSUE THREAD

**Issue by fgicquel** [android-rcs/rcsjta#179] opened 2015-12-18 10:06 UTC
When starting the RCS stack, 'HandlerThread' are created and started upon construction of IMS services (InstantMessagingService, RichcallService, Sip, Https, ...). 
After stopping the RCS stack, these threads are still running.
Step 1 : take a thread dump of the 'com.gsma.rcs' process  before starting the stack.
Step 2 : start the RCS stack.
Step 3 : stop the RCS stack.
Step 4 : take a new thread dump of the 'com.gsma.rcs' process.
Step 5 : start the RCS stack.
Step 6 : stop the RCS stack.
Step 7 : take a new thread dump of the 'com.gsma.rcs' process.

Expected result : the number of threads shall be the same in each thread dump.
Current result : by comparing the different thread dump, we noticed that the number of threads is increasing.

You will find in attachments examples of thread dumps.
[threads_report_initial_state.txt](https://github.com/android-rcs/rcsjta/files/66450/threads_report_initial_state.txt)
[threads_report_after_first_stop.txt](https://github.com/android-rcs/rcsjta/files/66451/threads_report_after_first_stop.txt)
[threads_report._after_second_stop.txt](https://github.com/android-rcs/rcsjta/files/66452/threads_report._after_second_stop.txt)

**Comment by yplo6403** [comment] 2016-01-07 14:48
Bug fixed with commit ID 4c326bbf527fbeedc87b74beb540def1b0cd3d0b

**Comment by yplo6403** [comment] 2016-01-22 10:02
Fixe introduced a regression. A NPE occurs if you call a method from the API while in air plane mode.
[NPE_openChat.txt](https://github.com/android-rcs/rcsjta/files/100598/NPE_openChat.txt)

**Comment by yplo6403** [comment] 2016-01-22 13:27
Bug fixed with commit:
commit 53fe391a980045f59e1f1c9c7bf82d37fec7bac7
Author: yplo6403 <philippe.lemordant@orange.com>
Date:   Fri Jan 22 14:26:03 2016 +0100

    Core: background handlers only quit operations if stop is due to TERMINATION_BY_SYSTEM
    When ims service stops, OperationHandlers will be set to null in
    currently implementation. This will cause null pointer exception
    when user trying to delete conversations during ims service stopped
    period, for example airplane mode or network loss.

    This patch fixed the issue by recreate OperationHandlers when ims
    service is stopped.

    Background operations are only stopped if termination is due to system (i.e. stack deactivation).
    Otherwise background handlers are kept and can be reused when network connection is recovered.

**Closed by yplo6403** 2016-01-22 13:27 UTC
